title: Anggi Nur Fauziah # your name (or website title) here
logo: "https://github.com/angginfauziah/angginfauziah.github.io/blob/main/images/foto%20angi.png?raw=true" # your photo (or logo) here
description: > # (remove <br> elements if you don't need line breaks)
  First description 
  <br>I am active in student and community activities. I am a hardworking person, easy to socialize
and can work well together in the team<br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/angginurfauziah/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
